require: rubocop-rails

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*

Naming/AccessorMethodName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
